# 不想启动某个IM就注释掉那一部分

# QQ
[Controller.QQ]
master = [29396282] # master user id , 账号 ID
account = 0
http_host = 'http://localhost:8080'   # Mirai http服务器
ws_host = 'http://localhost:8080'   # Mirai Websocket服务器
verify_key = ""
trigger = false
INTRO = "POWER BY ZAKURO"  # 后缀
ABOUT = "Created by Rama Agung Supriyadi" # 关于命令返回
WHITE = "Group NOT in WHITE list" # 黑白名单提示
proxy = { status = false, url = "http://127.0.0.1:7890" }

# Telegram
[Controller.Telegram]
master = [114, 514] # master user id , 账号 ID
botToken = '5624390876:AAFtmB-sV52rPNg3Ty6O1rPgmqUZDrLHViw' # 机器人密钥
trigger = false
INTRO = "POWER BY ZAKURO"  # 后缀
ABOUT = "Created by Rama Agung Supriyadi" # 关于命令返回
WHITE = "Group NOT in WHITE list" # 黑白名单提示
# 设置的代理，但是不代理 openai api, 只代理 bot
proxy = { status = false, url = "http://127.0.0.1:7890" }

# Base Event Api
[Controller.BaseServer]
host = "127.0.0.1"
port = 9559
